server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Customer-Details
          uri: lb://Customer-Details
          predicates:
            - Path=/customers/**
          filters:
            - name: CircuitBreaker
              args:
                name: Customer-Details
                fallbackuri: forward:/userServiceFallback


        -



hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMillieseconds: 5000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
